- name: Install Docker on Ubuntu                                                                                                                                   
  include_tasks: setup-ubuntu.yml                                                                                                                                               
  when: ansible_distribution == "Ubuntu"

- name: Install Docker on Debian                                                                                                                                   
  include_tasks: setup-debian.yml                                                                                                                                               
  when: ansible_distribution == "Debian"