- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.asc
    state: present
  when: ansible_distribution == "Ubuntu"



- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ansible_distribution}} stable
    filename: /etc/apt/sources.list.d/docker.list
    state: present

- name: Update apt and install docker
  apt:
    name: {{item}}
    state: latest
    update_cache: true
  with_items:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io 
    - docker-buildx-plugin 
    - docker-compose-plugin

- name: Ensure Docker group exists
  group:
    name: docker
    state: present
  register: docker_group

- name: Add User to docker group
  user:
    name: "{{user}}"
    groups: docker 
    append: true 
  when: docker_group is changed