---
# handlers file for docker
- name: start docker                                                                                                                                    
  ansible.builtin.service:                                                                                                                                               
    name: docker                                                                                                                                          
    state: started 
    enabled: true

- name: restart docker
  ansible.builtin.service:
    name: docker
    state: restarted