---
# handlers file for docker
- name: start docker                                                                                                                                    
  service:                                                                                                                                               
    name: docker                                                                                                                                          
    state: started 
    enabled: true

- name: restart docker
  service:
    name: docker
    state: restarted