---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: jammy
    image: jrei/systemd-ubuntu:20.04
provisioner:
  name: ansible
verifier:
  name: testinfra
scenario:
  name: default
  create_sequence:
    - create
  check_sequence:
    - destroy
    - dependency
    - create

